/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package web;

import java.awt.Frame;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author Fatih
 */
public class Antrenor extends javax.swing.JDialog {
    DefaultTableModel model;
    Web islemler = new Web();
    private Frame frame;
    /**
     * Creates new form Antrenor
     */
    public Antrenor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model = (DefaultTableModel) antrenor_tablo.getModel();
        antrenorGoruntule();
    }

    Antrenor(int id, String TCNO, String ad, String soyad, String TelefonNo, Date Dogumtarihi, String Password, String Tip, String Sube) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        antrenor_tablo = new javax.swing.JTable();
        arama_cubugu = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tc_alani = new javax.swing.JTextField();
        telefon_alani = new javax.swing.JTextField();
        ad_alani = new javax.swing.JTextField();
        soyad_alani = new javax.swing.JTextField();
        sifre_alani = new javax.swing.JTextField();
        mesaj_alani = new javax.swing.JLabel();
        antrenor_ekle = new javax.swing.JButton();
        tarih_alani = new javax.swing.JTextField();
        guncelle = new javax.swing.JButton();
        sil = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        brans_alani = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sube_alani = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        antrenor_tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TCNo", "Ad", "Soyad", "TelefonNo", "DoğumTarihi", "Password", "Branş", "Şube"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        antrenor_tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                antrenor_tabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(antrenor_tablo);
        if (antrenor_tablo.getColumnModel().getColumnCount() > 0) {
            antrenor_tablo.getColumnModel().getColumn(0).setResizable(false);
            antrenor_tablo.getColumnModel().getColumn(1).setResizable(false);
            antrenor_tablo.getColumnModel().getColumn(2).setResizable(false);
            antrenor_tablo.getColumnModel().getColumn(3).setResizable(false);
            antrenor_tablo.getColumnModel().getColumn(4).setResizable(false);
            antrenor_tablo.getColumnModel().getColumn(5).setResizable(false);
            antrenor_tablo.getColumnModel().getColumn(6).setResizable(false);
            antrenor_tablo.getColumnModel().getColumn(7).setResizable(false);
            antrenor_tablo.getColumnModel().getColumn(8).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 377, 729, 187));

        arama_cubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_cubuguKeyReleased(evt);
            }
        });
        getContentPane().add(arama_cubugu, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 106, 729, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 132, 729, 10));

        jLabel1.setText("TC No:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 177, -1, -1));

        jLabel2.setText("Ad:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 207, 33, -1));

        jLabel3.setText("Soyad:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 240, -1, -1));

        jLabel4.setText("Telefon No:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 269, -1, -1));

        jLabel5.setText("Doğum Tarihi:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 309, -1, -1));

        jLabel6.setText("Password:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 339, -1, -1));
        getContentPane().add(tc_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 177, 142, -1));
        getContentPane().add(telefon_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 266, 142, -1));
        getContentPane().add(ad_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 204, 142, -1));
        getContentPane().add(soyad_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 237, 142, -1));
        getContentPane().add(sifre_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 336, 142, -1));

        mesaj_alani.setForeground(new java.awt.Color(0, 255, 0));
        getContentPane().add(mesaj_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 336, 168, 23));

        antrenor_ekle.setText("Antrenör Ekle");
        antrenor_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antrenor_ekleActionPerformed(evt);
            }
        });
        getContentPane().add(antrenor_ekle, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 336, -1, -1));
        getContentPane().add(tarih_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 306, 142, -1));

        guncelle.setText("Güncelle");
        guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleActionPerformed(evt);
            }
        });
        getContentPane().add(guncelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 265, -1, -1));

        sil.setText("Sil");
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });
        getContentPane().add(sil, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 203, -1, -1));

        jLabel7.setText("Branş:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(831, 180, -1, -1));
        getContentPane().add(brans_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 177, 110, -1));

        jLabel8.setText("Şube:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 225, -1, -1));
        getContentPane().add(sube_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 222, 110, -1));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Antrenörler");

        back.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fatih\\Documents\\NetBeansProjects\\Web\\src\\web\\images\\icons8_undo_26px_1.png")); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(399, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void dinamikAra(String ara){
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        
        antrenor_tablo.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(ara));
    }
    private void arama_cubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_cubuguKeyReleased
        String ara = arama_cubugu.getText();
        
        dinamikAra(ara);
    }//GEN-LAST:event_arama_cubuguKeyReleased

    private void antrenor_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antrenor_ekleActionPerformed
        mesaj_alani.setText("");
        
        String TCNO = tc_alani.getText();
        String ad = ad_alani.getText();
        String soyad = soyad_alani.getText();
        String TelefonNo = telefon_alani.getText();
        String Dogumtarihi = tarih_alani.getText();
        String Password = sifre_alani.getText();
        String Tip = brans_alani.getText();
        String Sube = sube_alani.getText();
        
        islemler.antrenorEkle(TCNO,ad,soyad,TelefonNo,Dogumtarihi,Password,Tip,Sube);
        
        antrenorGoruntule();
        
        mesaj_alani.setText("Başarıyla eklendi.");
        
        
        
    }//GEN-LAST:event_antrenor_ekleActionPerformed

    private void antrenor_tabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_antrenor_tabloMouseClicked
        int selectedrow = antrenor_tablo.getSelectedRow();
        
        tc_alani.setText(model.getValueAt(selectedrow, 1).toString());
        ad_alani.setText(model.getValueAt(selectedrow, 2).toString());
        soyad_alani.setText(model.getValueAt(selectedrow, 3).toString());
        telefon_alani.setText(model.getValueAt(selectedrow, 4).toString());
        tarih_alani.setText(model.getValueAt(selectedrow, 5).toString());
        sifre_alani.setText(model.getValueAt(selectedrow, 6).toString());
        brans_alani.setText(model.getValueAt(selectedrow, 7).toString());
        sube_alani.setText(model.getValueAt(selectedrow, 8).toString());
    }//GEN-LAST:event_antrenor_tabloMouseClicked

    private void guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleActionPerformed
        String TCNO = tc_alani.getText();
        String ad = ad_alani.getText();
        String soyad = soyad_alani.getText();
        String TelefonNo = telefon_alani.getText();
        String Dogumtarihi = tarih_alani.getText();
        String Password = sifre_alani.getText();
        String Tip = brans_alani.getText();
        String Sube = sube_alani.getText();
        
        
        int selectedrow = antrenor_tablo.getSelectedRow();
        
        if(selectedrow == -1){
            
            if(model.getRowCount() == 0){
                mesaj_alani.setText("Tablo boş.");
            }
            else{
                mesaj_alani.setText("Antrenör seçin!");
            }
        }
        else{
            int id = (int)model.getValueAt(selectedrow, 0);
            
            islemler.antrenorGuncelle(id,TCNO,ad,soyad,TelefonNo,Dogumtarihi,Password);
            
            antrenorGoruntule();
            
            mesaj_alani.setText("Başarıyla güncellendi.");
        }
    }//GEN-LAST:event_guncelleActionPerformed

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed
        mesaj_alani.setText("");
        
        int selectedrow = antrenor_tablo.getSelectedRow();
        
        if(selectedrow == -1){
            if(model.getRowCount() == 0){
                mesaj_alani.setText("Tablo boş.");
            }
            else{
                mesaj_alani.setText("Antrenör seçin!");
            }
        }
        else{
            int id = (int)model.getValueAt(selectedrow,0);
            
            islemler.antrenorSil(id);
            
            antrenorGoruntule();
            
            mesaj_alani.setText("Başarıyla silindi.");
        }
    }//GEN-LAST:event_silActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        
        AdminPanel adminEkrani = new AdminPanel(frame,true);
        setVisible(false);
            
        adminEkrani.setVisible(true);
        System.exit(0);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public void antrenorGoruntule(){
        model.setRowCount(0); 
        
        ArrayList<AntrenorBilgi> antrenorler = new ArrayList<AntrenorBilgi>();
        
        antrenorler = islemler.antrenorGoster();
        
        if(antrenorler != null){
            for(AntrenorBilgi antrenor : antrenorler){
                Object[] eklenecek = {antrenor.getId(),antrenor.getTCNO(),antrenor.getAd(),antrenor.getSoyad(),antrenor.getTelefonNo(),antrenor.getDogumtarihi(),antrenor.getPassword(),antrenor.getTip(),antrenor.getSube()};
                model.addRow(eklenecek);
            }
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Antrenor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Antrenor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Antrenor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Antrenor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Antrenor dialog = new Antrenor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad_alani;
    private javax.swing.JButton antrenor_ekle;
    private javax.swing.JTable antrenor_tablo;
    private javax.swing.JTextField arama_cubugu;
    private javax.swing.JButton back;
    private javax.swing.JTextField brans_alani;
    private javax.swing.JButton guncelle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel mesaj_alani;
    private javax.swing.JTextField sifre_alani;
    private javax.swing.JButton sil;
    private javax.swing.JTextField soyad_alani;
    private javax.swing.JTextField sube_alani;
    private javax.swing.JTextField tarih_alani;
    private javax.swing.JTextField tc_alani;
    private javax.swing.JTextField telefon_alani;
    // End of variables declaration//GEN-END:variables

    
}
