/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package web;

import java.awt.Frame;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Fatih
 */
public class Uye extends javax.swing.JDialog {
    DefaultTableModel model;
    Web islemler = new Web();
    private Frame frame;
    /**
     * Creates new form Uye
     */
    public Uye(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model = (DefaultTableModel) uye_tablo.getModel();
        uyeGoruntule();
    }
    
    Uye(int uyeID, String TCNO, String ad, String soyad, String TelefonNo, String Adres, String Email, String Cinsiyet, Date Dogumtarihi, int Boy, int Kilo, int Indeks, String Tip, Date Basla, Date Bitis, int Uyelik, String Antrenor) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        uye_tablo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        mail_alani = new javax.swing.JTextField();
        adres_alani = new javax.swing.JTextField();
        tc_alani = new javax.swing.JTextField();
        ad_alani = new javax.swing.JTextField();
        telefon_alani = new javax.swing.JTextField();
        soyad_alani = new javax.swing.JTextField();
        boy_alani = new javax.swing.JTextField();
        kilo_alani = new javax.swing.JTextField();
        uye_ekle = new javax.swing.JButton();
        mesaj_alani = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dogum_alani = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cinsiyet_alani = new javax.swing.JTextField();
        uye_sil = new javax.swing.JButton();
        uyelik_liste = new javax.swing.JComboBox<>();
        antrenor_liste = new javax.swing.JComboBox<>();
        brans_liste = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        back = new javax.swing.JButton();
        uye_guncelle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uye_tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Üye ID", "TCNO", "Ad", "Soyad", "Telefon No", "Adres", "Email", "Cinsiyet", "Doğum Tarihi", "Indeks", "Branş", "Üyelik Süresi", "Antrenörü"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        uye_tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uye_tabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(uye_tablo);
        if (uye_tablo.getColumnModel().getColumnCount() > 0) {
            uye_tablo.getColumnModel().getColumn(0).setResizable(false);
            uye_tablo.getColumnModel().getColumn(1).setResizable(false);
            uye_tablo.getColumnModel().getColumn(2).setResizable(false);
            uye_tablo.getColumnModel().getColumn(3).setResizable(false);
            uye_tablo.getColumnModel().getColumn(4).setResizable(false);
            uye_tablo.getColumnModel().getColumn(5).setResizable(false);
            uye_tablo.getColumnModel().getColumn(6).setResizable(false);
            uye_tablo.getColumnModel().getColumn(7).setResizable(false);
            uye_tablo.getColumnModel().getColumn(8).setResizable(false);
            uye_tablo.getColumnModel().getColumn(9).setResizable(false);
            uye_tablo.getColumnModel().getColumn(10).setResizable(false);
            uye_tablo.getColumnModel().getColumn(11).setResizable(false);
            uye_tablo.getColumnModel().getColumn(12).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 261, 1007, 158));

        jLabel1.setText("TCNO:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, -1, -1));

        jLabel2.setText("Ad:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 104, -1, -1));

        jLabel3.setText("Soyad:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel4.setText("Telefon No:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 161, 64, -1));

        jLabel5.setText("Adres:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 201, -1, -1));

        jLabel6.setText("Doğum Tarihi:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 116, -1, -1));

        jLabel7.setText("Boy:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 154, -1, -1));

        jLabel8.setText("Kilo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 185, -1, -1));

        jLabel9.setText("Branş:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 89, -1, -1));

        jLabel10.setText("Üyelik Süresi:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 130, -1, -1));

        jLabel11.setText("Antrenörü:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 185, -1, -1));
        getContentPane().add(mail_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 223, 121, -1));
        getContentPane().add(adres_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 192, 121, -1));
        getContentPane().add(tc_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 121, -1));
        getContentPane().add(ad_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 101, 121, -1));
        getContentPane().add(telefon_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 158, 123, -1));
        getContentPane().add(soyad_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 127, 121, -1));
        getContentPane().add(boy_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 151, 130, -1));
        getContentPane().add(kilo_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 182, 130, -1));

        uye_ekle.setText("Ekle");
        uye_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uye_ekleActionPerformed(evt);
            }
        });
        getContentPane().add(uye_ekle, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 428, -1, -1));
        getContentPane().add(mesaj_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 428, 159, 23));

        jLabel13.setText("Email:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 226, -1, -1));
        getContentPane().add(dogum_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 113, 130, -1));

        jLabel14.setText("Cinsiyet:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 85, -1, -1));
        getContentPane().add(cinsiyet_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 82, 130, -1));

        uye_sil.setText("Sil");
        uye_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uye_silActionPerformed(evt);
            }
        });
        getContentPane().add(uye_sil, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 428, -1, -1));

        uyelik_liste.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30", "90", "180", "365" }));
        getContentPane().add(uyelik_liste, new org.netbeans.lib.awtextra.AbsoluteConstraints(667, 127, -1, -1));

        antrenor_liste.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fatih", "Selim", "Hakan", "Yunus" }));
        getContentPane().add(antrenor_liste, new org.netbeans.lib.awtextra.AbsoluteConstraints(667, 182, -1, -1));

        brans_liste.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sporcu", "Atlet", "Dövüşçü", "Bisikletçi" }));
        getContentPane().add(brans_liste, new org.netbeans.lib.awtextra.AbsoluteConstraints(667, 86, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Üyeler");

        back.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fatih\\Documents\\NetBeansProjects\\Web\\src\\web\\images\\icons8_undo_26px_1.png")); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addGap(425, 425, 425))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(463, 463, 463)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 60));

        uye_guncelle.setText("Güncelle");
        uye_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uye_guncelleActionPerformed(evt);
            }
        });
        getContentPane().add(uye_guncelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uye_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uye_ekleActionPerformed
        mesaj_alani.setText("");
        
        String TCNO = tc_alani.getText();
        String ad = ad_alani.getText();
        String soyad = soyad_alani.getText();
        String TelefonNo = telefon_alani.getText();
        String Adres = adres_alani.getText();
        String Email = mail_alani.getText();
        String Cinsiyet = cinsiyet_alani.getText();
        String Dogumtarihi = dogum_alani.getText();
        int Boy = Integer.parseInt(boy_alani.getText());
        int Kilo = Integer.parseInt(kilo_alani.getText());
        int Indeks = Kilo/(Boy*Boy);
        String Tip = brans_liste.getSelectedItem().toString();
        int Uyelik = Integer.parseInt(uyelik_liste.getSelectedItem().toString());
        String Antrenor = antrenor_liste.getSelectedItem().toString();
        
        
        islemler.uyeEkle(TCNO,ad,soyad,TelefonNo,Adres,Email,Cinsiyet,Dogumtarihi,Indeks,Tip,Uyelik,Antrenor);
        
        uyeGoruntule();
        
        mesaj_alani.setText("Başarıyla eklendi.");
    }//GEN-LAST:event_uye_ekleActionPerformed

    private void uye_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uye_silActionPerformed
        
        mesaj_alani.setText("");
        
        int selectedrow = uye_tablo.getSelectedRow();
        
        if(selectedrow == -1){
            if(model.getRowCount() == 0){
                mesaj_alani.setText("Tablo boş.");
            }
            else{
                mesaj_alani.setText("Üye seçin!");
            }
        }
        else{
            int id = (int)model.getValueAt(selectedrow,0);
            
            islemler.uyeSil(id);
            
            uyeGoruntule();
            
            mesaj_alani.setText("Başarıyla silindi.");
        }
    }//GEN-LAST:event_uye_silActionPerformed

    private void uye_tabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uye_tabloMouseClicked
        int selectedrow = uye_tablo.getSelectedRow();
        
        tc_alani.setText(model.getValueAt(selectedrow, 1).toString());
        ad_alani.setText(model.getValueAt(selectedrow, 2).toString());
        soyad_alani.setText(model.getValueAt(selectedrow, 3).toString());
        telefon_alani.setText(model.getValueAt(selectedrow, 4).toString());
        adres_alani.setText(model.getValueAt(selectedrow, 5).toString());
        mail_alani.setText(model.getValueAt(selectedrow, 6).toString());
        cinsiyet_alani.setText(model.getValueAt(selectedrow, 7).toString());
        dogum_alani.setText(model.getValueAt(selectedrow, 8).toString());
        /*boy_alani.setText(model.getValueAt(selectedrow, 9).toString());
        kilo_alani.setText(model.getValueAt(selectedrow, 10).toString());*/
        
    }//GEN-LAST:event_uye_tabloMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

        AntrenorPanel antrenorEkrani = new AntrenorPanel(frame,true);
        setVisible(false);

        antrenorEkrani.setVisible(true);
        System.exit(0);
    }//GEN-LAST:event_backActionPerformed

    private void uye_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uye_guncelleActionPerformed
        String TCNO = tc_alani.getText();
        String ad = ad_alani.getText();
        String soyad = soyad_alani.getText();
        String TelefonNo = telefon_alani.getText();
        String Adres = adres_alani.getText();
        String Email = mail_alani.getText();
        String Cinsiyet = cinsiyet_alani.getText();
        String Dogumtarihi = dogum_alani.getText();
        int Boy = Integer.parseInt(boy_alani.getText());
        int Kilo = Integer.parseInt(kilo_alani.getText());
        int Indeks = Kilo/(Boy*Boy);
        String Tip = brans_liste.getSelectedItem().toString();
        int Uyelik = Integer.parseInt(uyelik_liste.getSelectedItem().toString());
        String Antrenor = antrenor_liste.getSelectedItem().toString();
        
        
        int selectedrow = uye_tablo.getSelectedRow();
        
        if(selectedrow == -1){
            
            if(model.getRowCount() == 0){
                mesaj_alani.setText("Tablo boş.");
            }
            else{
                mesaj_alani.setText("Üye seçin!");
            }
        }
        else{
            int uyeID = (int)model.getValueAt(selectedrow, 0);
            
            islemler.uyeGuncelle(uyeID,TCNO,ad,soyad,TelefonNo,Adres,Email,Cinsiyet,Dogumtarihi,Boy,Kilo,Tip,Uyelik,Antrenor);
            
            uyeGoruntule();
            
            mesaj_alani.setText("Başarıyla güncellendi.");
        }
    }//GEN-LAST:event_uye_guncelleActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void uyeGoruntule(){
        model.setRowCount(0); 
        
        ArrayList<UyeBilgi> uyeler = new ArrayList<UyeBilgi>();
        
        uyeler = islemler.uyeGoster();
        
        if(uyeler != null){
            for(UyeBilgi uye : uyeler){
                Object[] eklenecek = {uye.getUyeID(),uye.getTCNO(),uye.getAd(),uye.getSoyad(),uye.getTelefonNo(),uye.getAdres(),uye.getEmail(),uye.getCinsiyet(),uye.getDogumtarihi(),uye.getIndeks(),uye.getTip(),uye.getUyelik(),uye.getAntrenor()};
                model.addRow(eklenecek);
            }
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Uye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Uye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Uye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Uye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Uye dialog = new Uye(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad_alani;
    private javax.swing.JTextField adres_alani;
    private javax.swing.JComboBox<String> antrenor_liste;
    private javax.swing.JButton back;
    private javax.swing.JTextField boy_alani;
    private javax.swing.JComboBox<String> brans_liste;
    private javax.swing.JTextField cinsiyet_alani;
    private javax.swing.JTextField dogum_alani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField kilo_alani;
    private javax.swing.JTextField mail_alani;
    private javax.swing.JLabel mesaj_alani;
    private javax.swing.JTextField soyad_alani;
    private javax.swing.JTextField tc_alani;
    private javax.swing.JTextField telefon_alani;
    private javax.swing.JButton uye_ekle;
    private javax.swing.JButton uye_guncelle;
    private javax.swing.JButton uye_sil;
    private javax.swing.JTable uye_tablo;
    private javax.swing.JComboBox<String> uyelik_liste;
    // End of variables declaration//GEN-END:variables
}
